version: '3.7'

volumes:
  mysql_data: {}
  influxdb_data: {}

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    hostname: frontend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /app
    volumes:
      - ~/.npmrc:/root/.npmrc
      - ~/.npmrc:/home/node/.npmrc
      - ~/.npm/:/home/node/.npm
      # Activate for live reload in dev mode
      - ./frontend:/app
    ports:
      - '4200:4200'
    depends_on:
      - db
      - db-testing
      - influxdb
      - phpmyadmin
    environment:
      APP_MAIN_BACKEND_URL: http://backend:3888
    networks:
      - local_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    hostname: backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /app
    volumes:
      - ~/.npmrc:/root/.npmrc
      - ~/.npmrc:/home/node/.npmrc
      - ~/.npm/:/home/node/.npm
      # Activate for live reload in dev mode
      - ./backend:/app
    ports:
      - '3888:3888'
    depends_on:
      - db
      - db-testing
      - influxdb
      - phpmyadmin
    environment:
      APP_PORT_ANOMALY_DETECTION_BACKEND: 3888
      APP_DB_HOST: db
      APP_DB_USER: app
      APP_DB_PASS: app
      APP_DB_NAME: app
      APP_TEST_DB_HOST: db-testing
      APP_TEST_DB_USER: root
      APP_TEST_DB_PASS: root
      APP_TEST_DB_NAME: app-testing
      APP_TEST_DB_PORT: 3307
    networks:
      - local_net

  # ---------------------
  # MYSQL DB
  # ---------------------
  db:
    image: mysql:8.0.28-oracle
    hostname: db
    ports:
      - 3306:3306
    command: >-
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    networks:
      - local_net
    volumes:
      - ~/mysql_data:/var/lib/mysql

  # ---------------------
  # MYSQL DB TESTING
  # ---------------------
  db-testing:
    image: mysql:8.0.28-oracle
    hostname: db-testing
    ports:
      - 3307:3306
    command: >-
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app-testing
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root

  # ---------------------
  # INFLUXDB
  # ---------------------
  influxdb:
    image: influxdb:2.6
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin54321
      DOCKER_INFLUXDB_INIT_ORG: admin_org
      DOCKER_INFLUXDB_INIT_BUCKET: admin_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin_tocken
      INFLUXDB_LOGGING_LEVEL: error
    ports:
      - '8086:8086'
    networks:
      - local_net
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # ---------------------
  # PHP MY ADMIN
  # ---------------------
  phpmyadmin:
    image: phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8079:80
    environment:
      PMA_HOSTS: >-
        db, db-testing,
      PMA_USER: app
      PMA_PASSWORD: app
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1024M
    networks:
      - local_net

  # add Grafana
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
